version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_install:
      - pip install .
      - medicure

python:
  install:
    - requirements: requirements/main.txt
    - requirements: requirements/documentation.txt
