language: python

python:
  - 3.8
  - 3.9

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/default.txt
  - python setup.py install
  - python -m perke download

script:
  - pytest
