language: python

python:
  - 3.8
  - 3.9

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/default.txt
  - wget https://github.com/sobhe/hazm/releases/download/v0.5/resources-0.5.zip
  - unzip resources-0.5.zip -d perke/resources

script:
  - pytest