blank_issues_enabled: true
contact_links:
  - name: Questions about Perke
    url: https://github.com/alirezatheh/perke/discussions/new?category=q-a
    about: Ask questions about usage of Perke.
  - name: Discussions and Ideas
    url: https://github.com/alirezatheh/perke/discussions
    about: Talk about new algorithms, models, show your latest application of Perke.
